on: push
name: Check package version
jobs:
  checkVersion:
    name: Check package version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 3
      - name: Extract branch name
        uses: mdecoleman/pr-branch-name@1.0.0
        id: extract_branch
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      # Use this GitHub Action
      - name: Check package version
        uses: technote-space/package-version-check-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: release/

      - name: Create Release PullRequest
        if: startsWith(steps.extract_branch.outputs.branch, 'release')
        uses: peter-evans/create-pull-request@v3
        with:
          author: ${{ github.actor }}
          branch: ${{ steps.extract_branch.outputs.branch }}
          title: ${{ steps.extract_branch.outputs.branch }}
          body: |
            更新内容
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

          labels: |
            release
          assignees: maintainers
          reviewers: maintainers
          team-reviewers: |
            owners
            maintainers
